theme: jekyll-theme-cayman
title: Data Science Portfolio
description: Thomas Algenio
custom_link: https://github.com/thomasalgenio/Sample_Projects/tree/main
<p class="github">
  <a href="{{ site.custom_link }}" target="_blank">Visit My Work</a>
</p>
